import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Session } from 'next-auth';
import AppWrapper from './components/app-wrapper';
import { cn } from './libs/cn';
import Overlay from './components/overlay';
import Spinner from './components/spinner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  auth,
  children,
}: Readonly<{
  session: Session | null;
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('bg-orange-700 text-white ', inter.className)}>
        <Spinner />
        <AppWrapper>
          <Overlay>
            <div className="container mx-auto">{children}</div>
          </Overlay>
          {auth}
        </AppWrapper>
      </body>
    </html>
  );
}
