import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { Session } from 'next-auth';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  session,
  auth,
  children,
}: Readonly<{
  session: Session | null;
  auth: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Link href="/signin">Open Modal</Link>
          <div>{children}</div>
          <div>{auth}</div>
        </body>
      </html>
    </SessionProvider>
  );
}
