import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AppWrapper from './components/app-wrapper';
import { cn } from './libs/cn';
import TopLine from './components/top-line';
import Sidebar from './components/sidebar';
import Overlay from './components/overlay';
import Breadcrumbs from './components/breadcrumbs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
  profile,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
  profile: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('bg-customBackground text-primary-foreground overflow-x-hidden line-numbers', inter.className)}
      >
        <AppWrapper>
          <Overlay>
            <Sidebar />
            <div className="container mx-auto h-screen">
              <TopLine />
              <Breadcrumbs />
              {children}
            </div>
          </Overlay>
          {auth}
          {profile}
        </AppWrapper>
      </body>
    </html>
  );
}
